### ISSUE TITLE
Markdown Tables don't convert to HTML in Episode Notes

### ISSUE THREAD

**Issue by spilth** [AnnotatedSpring/annotated-spring#18]
Tables like the following do not convert to HTML when used in Episode Notes. This might be due to lack of support in Pegdown or some missing configuration option.

| Path             | HTTP Verb | Controller Method | Purpose                                  |
|------------------|-----------|-------------------|------------------------------------------|
| /notes           | GET       | index             | List all Notes                           |
| /notes/new       | GET       | new               | Render form for creating a new Note      |
| /notes           | POST      | create            | Create a new Note                        |
| /notes/{id}      | GET       | show              | Display a specific Note                  |

**Comment by brunolellis** [comment]
Hi, Brian!

I tried to fix this issue with pull request #24.

There are some details that I don't know how to deal with:
1) Design/CSS to beautify tables. At least the HTML is rendered now;
2) I've never worked with pegdown, but I could find out that the problem was with Extensions.TABLES as stated [here](https://github.com/sirthias/pegdown/issues/81) and [here](https://github.com/sirthias/pegdown#introduction).

There are some nice and useful (I think...) [Extensions](https://github.com/sirthias/pegdown#introduction) like *TASKLISTITEMS*.

I am new to git and github, so I'm sorry if I've been doing something wrong or not in a standard way. Feel free to tell me a better way :smiley:

**Comment by spilth** [comment]
I'll take a look at the other extensions to see what might be useful to have. I was wanting table support for the table in Episode 4 - <https://github.com/AnnotatedSpring/episode-004#crud-url-convention>.

I guess the one challenge is getting Bootstrap's `table` class on the table element... Could probably do that with some JQuery at some point but I'm not too worried about it right now.

I need to make a Contributions section in the README to let people know how best to make pull requests but yours have been fine so far. I did add a note to #24 about cleaning up the test a little bit, thought.

Thanks again for your help!

**Comment by brunolellis** [comment]
Check this CSS workaround. It is not "bootstraped", but might work until you decide about a better solution:
```css
table {
  width: 100%;
}

table th {
  text-align: center;
}

table th, 
table td {
  padding: 1rem;
  line-height: 20px;
  border: 1px solid #DDD;
}
```

**Comment by spilth** [comment]
I added code to swap out `<table>` with `<table class="table">` when it's done with the Markdown processing.
